cleaner.settings:
  type: config_object
  label: 'Cleaner settings'
  mapping:
    cleaner_cron:
      type: integer
      label: 'Cleaner Cron settings'
    cleaner_last_cron:
      type: integer
      label: 'Cleaner Last Cron settings'
    cleaner_clear_cache:
      type: boolean
      label: 'Cleaner cache clearing settings'
    cleaner_additional_tables:
      type: string
      label: 'Cleaner additional tables clearing settings'
    cleaner_empty_watchdog:
      type: boolean
      label: 'Cleaner watchdog clearing settings'
    cleaner_clean_sessions:
      type: boolean
      label: 'Cleaner expired sessions clearing settings'
    cleaner_optimize_db:
      type: integer
      label: 'Cleaner DB optimizing settings'
